package com.laanait.shop.model;

// Generated 25 janv. 2012 13:59:40 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AdsCompanies generated by hbm2java
 */
public class AdsCompanies implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer adsCompaniesId;
	private Companies companies;
	private String adsCompaniesDescription;
	private String adsCompaniesImage;
	private int adsCompaniesCategory;
	private Date adsCompaniesSDate;
	private Date adsCompaniesEDate;
	private int adsCompaniesStatus;
	private Date adsCompanyDate;

	public AdsCompanies() {
	}

	public AdsCompanies(Companies companies, String adsCompaniesDescription,
			String adsCompaniesImage, int adsCompaniesCategory,
			Date adsCompaniesSDate, Date adsCompaniesEDate,
			int adsCompaniesStatus, Date adsCompanyDate) {
		this.companies = companies;
		this.adsCompaniesDescription = adsCompaniesDescription;
		this.adsCompaniesImage = adsCompaniesImage;
		this.adsCompaniesCategory = adsCompaniesCategory;
		this.adsCompaniesSDate = adsCompaniesSDate;
		this.adsCompaniesEDate = adsCompaniesEDate;
		this.adsCompaniesStatus = adsCompaniesStatus;
		this.adsCompanyDate = adsCompanyDate;
	}

	public Integer getAdsCompaniesId() {
		return this.adsCompaniesId;
	}

	public void setAdsCompaniesId(Integer adsCompaniesId) {
		this.adsCompaniesId = adsCompaniesId;
	}

	public Companies getCompanies() {
		return this.companies;
	}

	public void setCompanies(Companies companies) {
		this.companies = companies;
	}

	public String getAdsCompaniesDescription() {
		return this.adsCompaniesDescription;
	}

	public void setAdsCompaniesDescription(String adsCompaniesDescription) {
		this.adsCompaniesDescription = adsCompaniesDescription;
	}

	public String getAdsCompaniesImage() {
		return this.adsCompaniesImage;
	}

	public void setAdsCompaniesImage(String adsCompaniesImage) {
		this.adsCompaniesImage = adsCompaniesImage;
	}

	public int getAdsCompaniesCategory() {
		return this.adsCompaniesCategory;
	}

	public void setAdsCompaniesCategory(int adsCompaniesCategory) {
		this.adsCompaniesCategory = adsCompaniesCategory;
	}

	public Date getAdsCompaniesSDate() {
		return this.adsCompaniesSDate;
	}

	public void setAdsCompaniesSDate(Date adsCompaniesSDate) {
		this.adsCompaniesSDate = adsCompaniesSDate;
	}

	public Date getAdsCompaniesEDate() {
		return this.adsCompaniesEDate;
	}

	public void setAdsCompaniesEDate(Date adsCompaniesEDate) {
		this.adsCompaniesEDate = adsCompaniesEDate;
	}

	public int getAdsCompaniesStatus() {
		return this.adsCompaniesStatus;
	}

	public void setAdsCompaniesStatus(int adsCompaniesStatus) {
		this.adsCompaniesStatus = adsCompaniesStatus;
	}

	public Date getAdsCompanyDate() {
		return this.adsCompanyDate;
	}

	public void setAdsCompanyDate(Date adsCompanyDate) {
		this.adsCompanyDate = adsCompanyDate;
	}

}
