package com.laanait.shop.model;

// default package
// Generated 20 nov. 2011 19:45:07 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
public class Categories implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer categoryId;
	private String categoryName;
	private String categoryDescription;
	private Integer categoryParent;
	private Set<ShopsCategories> shopsCategorieses = new HashSet<ShopsCategories>(0);
	private Set<CompaniesCategories> companiesCategorieses = new HashSet<CompaniesCategories>(0);
	private Set<Products> productses = new HashSet<Products>(0);

	public Categories() {
	}

	public Categories(String categoryName, String categoryDescription,
			Integer categoryParent, Set<ShopsCategories> shopsCategorieses,
			Set<CompaniesCategories> companiesCategorieses, Set<Products> productses) {
		this.categoryName = categoryName;
		this.categoryDescription = categoryDescription;
		this.categoryParent = categoryParent;
		this.shopsCategorieses = shopsCategorieses;
		this.companiesCategorieses = companiesCategorieses;
		this.productses = productses;
	}

	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public String getCategoryDescription() {
		return this.categoryDescription;
	}

	public void setCategoryDescription(String categoryDescription) {
		this.categoryDescription = categoryDescription;
	}

	public Integer getCategoryParent() {
		return this.categoryParent;
	}

	public void setCategoryParent(Integer categoryParent) {
		this.categoryParent = categoryParent;
	}

	public Set<ShopsCategories> getShopsCategorieses() {
		return this.shopsCategorieses;
	}

	public void setShopsCategorieses(Set<ShopsCategories> shopsCategorieses) {
		this.shopsCategorieses = shopsCategorieses;
	}

	public Set<CompaniesCategories> getCompaniesCategorieses() {
		return this.companiesCategorieses;
	}

	public void setCompaniesCategorieses(Set<CompaniesCategories> companiesCategorieses) {
		this.companiesCategorieses = companiesCategorieses;
	}

	public Set<Products> getProductses() {
		return this.productses;
	}

	public void setProductses(Set<Products> productses) {
		this.productses = productses;
	}

}
