package com.laanait.shop.model;

// Generated 20 nov. 2011 22:24:37 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Companies generated by hbm2java
 */
public class Companies implements java.io.Serializable {

	private Integer companyId;
	private String companyName;
	private String companyAddress;
	private int companyPhone;
	private int companyEmail;
	private Date companyJoinDate;
	private int companyStatus;
	private Set logses = new HashSet(0);
	private Set adsCompanieses = new HashSet(0);
	private Set userses = new HashSet(0);
	private Set companiesCategorieses = new HashSet(0);

	public Companies() {
	}

	public Companies(String companyName, String companyAddress,
			int companyPhone, int companyEmail, Date companyJoinDate,
			int companyStatus) {
		this.companyName = companyName;
		this.companyAddress = companyAddress;
		this.companyPhone = companyPhone;
		this.companyEmail = companyEmail;
		this.companyJoinDate = companyJoinDate;
		this.companyStatus = companyStatus;
	}

	public Companies(String companyName, String companyAddress,
			int companyPhone, int companyEmail, Date companyJoinDate,
			int companyStatus, Set logses, Set adsCompanieses, Set userses,
			Set companiesCategorieses) {
		this.companyName = companyName;
		this.companyAddress = companyAddress;
		this.companyPhone = companyPhone;
		this.companyEmail = companyEmail;
		this.companyJoinDate = companyJoinDate;
		this.companyStatus = companyStatus;
		this.logses = logses;
		this.adsCompanieses = adsCompanieses;
		this.userses = userses;
		this.companiesCategorieses = companiesCategorieses;
	}

	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getCompanyAddress() {
		return this.companyAddress;
	}

	public void setCompanyAddress(String companyAddress) {
		this.companyAddress = companyAddress;
	}

	public int getCompanyPhone() {
		return this.companyPhone;
	}

	public void setCompanyPhone(int companyPhone) {
		this.companyPhone = companyPhone;
	}

	public int getCompanyEmail() {
		return this.companyEmail;
	}

	public void setCompanyEmail(int companyEmail) {
		this.companyEmail = companyEmail;
	}

	public Date getCompanyJoinDate() {
		return this.companyJoinDate;
	}

	public void setCompanyJoinDate(Date companyJoinDate) {
		this.companyJoinDate = companyJoinDate;
	}

	public int getCompanyStatus() {
		return this.companyStatus;
	}

	public void setCompanyStatus(int companyStatus) {
		this.companyStatus = companyStatus;
	}

	public Set getLogses() {
		return this.logses;
	}

	public void setLogses(Set logses) {
		this.logses = logses;
	}

	public Set getAdsCompanieses() {
		return this.adsCompanieses;
	}

	public void setAdsCompanieses(Set adsCompanieses) {
		this.adsCompanieses = adsCompanieses;
	}

	public Set getUserses() {
		return this.userses;
	}

	public void setUserses(Set userses) {
		this.userses = userses;
	}

	public Set getCompaniesCategorieses() {
		return this.companiesCategorieses;
	}

	public void setCompaniesCategorieses(Set companiesCategorieses) {
		this.companiesCategorieses = companiesCategorieses;
	}

}
