package com.laanait.shop.model;

// Generated 25 janv. 2012 13:59:40 by Hibernate Tools 3.4.0.CR1

/**
 * CompaniesCategoriesId generated by hbm2java
 */
public class CompaniesCategoriesId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int companyId;
	private int categoryId;
	private int categoriesCategoryId;

	public CompaniesCategoriesId() {
	}

	public CompaniesCategoriesId(int companyId, int categoryId,
			int categoriesCategoryId) {
		this.companyId = companyId;
		this.categoryId = categoryId;
		this.categoriesCategoryId = categoriesCategoryId;
	}

	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	public int getCategoriesCategoryId() {
		return this.categoriesCategoryId;
	}

	public void setCategoriesCategoryId(int categoriesCategoryId) {
		this.categoriesCategoryId = categoriesCategoryId;
	}

}
