package com.laanait.shop.model;

// Generated 25 janv. 2012 13:59:40 by Hibernate Tools 3.4.0.CR1

/**
 * CompaniesCategories generated by hbm2java
 */
public class CompaniesCategories implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private CompaniesCategoriesId id;
	private Companies companies;
	private Categories categories;

	public CompaniesCategories() {
	}

	public CompaniesCategories(CompaniesCategoriesId id, Companies companies,
			Categories categories) {
		this.id = id;
		this.companies = companies;
		this.categories = categories;
	}

	public CompaniesCategoriesId getId() {
		return this.id;
	}

	public void setId(CompaniesCategoriesId id) {
		this.id = id;
	}

	public Companies getCompanies() {
		return this.companies;
	}

	public void setCompanies(Companies companies) {
		this.companies = companies;
	}

	public Categories getCategories() {
		return this.categories;
	}

	public void setCategories(Categories categories) {
		this.categories = categories;
	}

}
