package com.laanait.shop.model;

// Generated 20 nov. 2011 22:24:37 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * LogsId generated by hbm2java
 */
public class LogsId implements java.io.Serializable {

	private int logId;
	private String logName;
	private int logDescription;
	private Date logDate;
	private int userId;
	private int companyId;
	private int shopId;
	private int productId;
	private int promoProductsId;

	public LogsId() {
	}

	public LogsId(int logId, String logName, int logDescription, Date logDate,
			int userId, int companyId, int shopId, int productId,
			int promoProductsId) {
		this.logId = logId;
		this.logName = logName;
		this.logDescription = logDescription;
		this.logDate = logDate;
		this.userId = userId;
		this.companyId = companyId;
		this.shopId = shopId;
		this.productId = productId;
		this.promoProductsId = promoProductsId;
	}

	public int getLogId() {
		return this.logId;
	}

	public void setLogId(int logId) {
		this.logId = logId;
	}

	public String getLogName() {
		return this.logName;
	}

	public void setLogName(String logName) {
		this.logName = logName;
	}

	public int getLogDescription() {
		return this.logDescription;
	}

	public void setLogDescription(int logDescription) {
		this.logDescription = logDescription;
	}

	public Date getLogDate() {
		return this.logDate;
	}

	public void setLogDate(Date logDate) {
		this.logDate = logDate;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	public int getShopId() {
		return this.shopId;
	}

	public void setShopId(int shopId) {
		this.shopId = shopId;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public int getPromoProductsId() {
		return this.promoProductsId;
	}

	public void setPromoProductsId(int promoProductsId) {
		this.promoProductsId = promoProductsId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LogsId))
			return false;
		LogsId castOther = (LogsId) other;

		return (this.getLogId() == castOther.getLogId())
				&& ((this.getLogName() == castOther.getLogName()) || (this
						.getLogName() != null && castOther.getLogName() != null && this
						.getLogName().equals(castOther.getLogName())))
				&& (this.getLogDescription() == castOther.getLogDescription())
				&& ((this.getLogDate() == castOther.getLogDate()) || (this
						.getLogDate() != null && castOther.getLogDate() != null && this
						.getLogDate().equals(castOther.getLogDate())))
				&& (this.getUserId() == castOther.getUserId())
				&& (this.getCompanyId() == castOther.getCompanyId())
				&& (this.getShopId() == castOther.getShopId())
				&& (this.getProductId() == castOther.getProductId())
				&& (this.getPromoProductsId() == castOther.getPromoProductsId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLogId();
		result = 37 * result
				+ (getLogName() == null ? 0 : this.getLogName().hashCode());
		result = 37 * result + this.getLogDescription();
		result = 37 * result
				+ (getLogDate() == null ? 0 : this.getLogDate().hashCode());
		result = 37 * result + this.getUserId();
		result = 37 * result + this.getCompanyId();
		result = 37 * result + this.getShopId();
		result = 37 * result + this.getProductId();
		result = 37 * result + this.getPromoProductsId();
		return result;
	}

}
