package com.laanait.shop.model;

// default package
// Generated 20 nov. 2011 19:45:07 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer productId;
	private String productName;
	private String productDescription;
	private String productImage;
	private BigDecimal productPrice;
	private int productShop;
	private Date productDate;
	private Set<Logs> logses = new HashSet<Logs>(0);
	private Set<AdsProducts> adsProductses = new HashSet<AdsProducts>(0);
	private Set<Categories> categorieses = new HashSet<Categories>(0);
	private Set<ProductsPromo> productsPromos = new HashSet<ProductsPromo>(0);

	public Products() {
	}

	public Products(int productShop, Date productDate) {
		this.productShop = productShop;
		this.productDate = productDate;
	}

	public Products(String productName, String productDescription,
			String productImage, BigDecimal productPrice, int productShop,
			Date productDate, Set<Logs> logses, Set<AdsProducts> adsProductses, Set<Categories> categorieses,
			Set<ProductsPromo> productsPromos) {
		this.productName = productName;
		this.productDescription = productDescription;
		this.productImage = productImage;
		this.productPrice = productPrice;
		this.productShop = productShop;
		this.productDate = productDate;
		this.logses = logses;
		this.adsProductses = adsProductses;
		this.categorieses = categorieses;
		this.productsPromos = productsPromos;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getProductDescription() {
		return this.productDescription;
	}

	public void setProductDescription(String productDescription) {
		this.productDescription = productDescription;
	}

	public String getProductImage() {
		return this.productImage;
	}

	public void setProductImage(String productImage) {
		this.productImage = productImage;
	}

	public BigDecimal getProductPrice() {
		return this.productPrice;
	}

	public void setProductPrice(BigDecimal productPrice) {
		this.productPrice = productPrice;
	}

	public int getProductShop() {
		return this.productShop;
	}

	public void setProductShop(int productShop) {
		this.productShop = productShop;
	}

	public Date getProductDate() {
		return this.productDate;
	}

	public void setProductDate(Date productDate) {
		this.productDate = productDate;
	}

	public Set<Logs> getLogses() {
		return this.logses;
	}

	public void setLogses(Set<Logs> logses) {
		this.logses = logses;
	}

	public Set<AdsProducts> getAdsProductses() {
		return this.adsProductses;
	}

	public void setAdsProductses(Set<AdsProducts> adsProductses) {
		this.adsProductses = adsProductses;
	}

	public Set<Categories> getCategorieses() {
		return this.categorieses;
	}

	public void setCategorieses(Set<Categories> categorieses) {
		this.categorieses = categorieses;
	}

	public Set<ProductsPromo> getProductsPromos() {
		return this.productsPromos;
	}

	public void setProductsPromos(Set<ProductsPromo> productsPromos) {
		this.productsPromos = productsPromos;
	}

}
