package com.laanait.shop.model;

// Generated 20 nov. 2011 22:24:37 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer productId;
	private String productName;
	private String productDescription;
	private String productImage;
	private BigDecimal productPrice;
	private int productShop;
	private Date productDate;
	private Set<?> logses = new HashSet<Object>(0);
	private Set<?> adsProductses = new HashSet<Object>(0);
	private Set<?> categorieses = new HashSet<Object>(0);
	private Set<?> productsPromos = new HashSet<Object>(0);

	public Products() {
	}

	public Products(int productShop, Date productDate) {
		this.productShop = productShop;
		this.productDate = productDate;
	}

	public Products(String productName, String productDescription,
			String productImage, BigDecimal productPrice, int productShop,
			Date productDate, Set<?> logses, Set<?> adsProductses, Set<?> categorieses,
			Set<?> productsPromos) {
		this.productName = productName;
		this.productDescription = productDescription;
		this.productImage = productImage;
		this.productPrice = productPrice;
		this.productShop = productShop;
		this.productDate = productDate;
		this.logses = logses;
		this.adsProductses = adsProductses;
		this.categorieses = categorieses;
		this.productsPromos = productsPromos;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getProductDescription() {
		return this.productDescription;
	}

	public void setProductDescription(String productDescription) {
		this.productDescription = productDescription;
	}

	public String getProductImage() {
		return this.productImage;
	}

	public void setProductImage(String productImage) {
		this.productImage = productImage;
	}

	public BigDecimal getProductPrice() {
		return this.productPrice;
	}

	public void setProductPrice(BigDecimal productPrice) {
		this.productPrice = productPrice;
	}

	public int getProductShop() {
		return this.productShop;
	}

	public void setProductShop(int productShop) {
		this.productShop = productShop;
	}

	public Date getProductDate() {
		return this.productDate;
	}

	public void setProductDate(Date productDate) {
		this.productDate = productDate;
	}

	public Set<?> getLogses() {
		return this.logses;
	}

	public void setLogses(Set<?> logses) {
		this.logses = logses;
	}

	public Set<?> getAdsProductses() {
		return this.adsProductses;
	}

	public void setAdsProductses(Set<?> adsProductses) {
		this.adsProductses = adsProductses;
	}

	public Set<?> getCategorieses() {
		return this.categorieses;
	}

	public void setCategorieses(Set<?> categorieses) {
		this.categorieses = categorieses;
	}

	public Set<?> getProductsPromos() {
		return this.productsPromos;
	}

	public void setProductsPromos(Set<?> productsPromos) {
		this.productsPromos = productsPromos;
	}

}
