package com.laanait.shop.model;

// Generated 25 janv. 2012 13:59:40 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProductsPromo generated by hbm2java
 */
public class ProductsPromo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer promoProductsId;
	private Products products;
	private Date promoProductsSDate;
	private Date promoProductsEDate;
	private int promoProductsStatus;
	private Date promoProductsDate;
	private Set<?> logses = new HashSet<Object>(0);

	public ProductsPromo() {
	}

	public ProductsPromo(Products products, Date promoProductsSDate,
			Date promoProductsEDate, int promoProductsStatus,
			Date promoProductsDate) {
		this.products = products;
		this.promoProductsSDate = promoProductsSDate;
		this.promoProductsEDate = promoProductsEDate;
		this.promoProductsStatus = promoProductsStatus;
		this.promoProductsDate = promoProductsDate;
	}

	public ProductsPromo(Products products, Date promoProductsSDate,
			Date promoProductsEDate, int promoProductsStatus,
			Date promoProductsDate, Set<?> logses) {
		this.products = products;
		this.promoProductsSDate = promoProductsSDate;
		this.promoProductsEDate = promoProductsEDate;
		this.promoProductsStatus = promoProductsStatus;
		this.promoProductsDate = promoProductsDate;
		this.logses = logses;
	}

	public Integer getPromoProductsId() {
		return this.promoProductsId;
	}

	public void setPromoProductsId(Integer promoProductsId) {
		this.promoProductsId = promoProductsId;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public Date getPromoProductsSDate() {
		return this.promoProductsSDate;
	}

	public void setPromoProductsSDate(Date promoProductsSDate) {
		this.promoProductsSDate = promoProductsSDate;
	}

	public Date getPromoProductsEDate() {
		return this.promoProductsEDate;
	}

	public void setPromoProductsEDate(Date promoProductsEDate) {
		this.promoProductsEDate = promoProductsEDate;
	}

	public int getPromoProductsStatus() {
		return this.promoProductsStatus;
	}

	public void setPromoProductsStatus(int promoProductsStatus) {
		this.promoProductsStatus = promoProductsStatus;
	}

	public Date getPromoProductsDate() {
		return this.promoProductsDate;
	}

	public void setPromoProductsDate(Date promoProductsDate) {
		this.promoProductsDate = promoProductsDate;
	}

	public Set<?> getLogses() {
		return this.logses;
	}

	public void setLogses(Set<?> logses) {
		this.logses = logses;
	}

}
