package com.laanait.shop.model;

// Generated 25 janv. 2012 13:59:40 by Hibernate Tools 3.4.0.CR1

/**
 * ShopsCategoriesId generated by hbm2java
 */
public class ShopsCategoriesId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int shopId;
	private int categoryId;
	private int categoriesCategoryId;

	public ShopsCategoriesId() {
	}

	public ShopsCategoriesId(int shopId, int categoryId,
			int categoriesCategoryId) {
		this.shopId = shopId;
		this.categoryId = categoryId;
		this.categoriesCategoryId = categoriesCategoryId;
	}

	public int getShopId() {
		return this.shopId;
	}

	public void setShopId(int shopId) {
		this.shopId = shopId;
	}

	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	public int getCategoriesCategoryId() {
		return this.categoriesCategoryId;
	}

	public void setCategoriesCategoryId(int categoriesCategoryId) {
		this.categoriesCategoryId = categoriesCategoryId;
	}

}
