package com.laanait.shop.model;

// Generated 25 janv. 2012 13:59:40 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer userId;
	private String userEmail;
	private String userPassword;
	private Set<?> logses = new HashSet<Object>(0);
	private Set<?> shopses = new HashSet<Object>(0);
	private Set<?> companieses = new HashSet<Object>(0);

	public Users() {
	}

	public Users(String userEmail, String userPassword) {
		this.userEmail = userEmail;
		this.userPassword = userPassword;
	}

	public Users(String userEmail, String userPassword, Set<?> logses,
			Set<?> shopses, Set<?> companieses) {
		this.userEmail = userEmail;
		this.userPassword = userPassword;
		this.logses = logses;
		this.shopses = shopses;
		this.companieses = companieses;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public Set<?> getLogses() {
		return this.logses;
	}

	public void setLogses(Set<?> logses) {
		this.logses = logses;
	}

	public Set<?> getShopses() {
		return this.shopses;
	}

	public void setShopses(Set<?> shopses) {
		this.shopses = shopses;
	}

	public Set<?> getCompanieses() {
		return this.companieses;
	}

	public void setCompanieses(Set<?> companieses) {
		this.companieses = companieses;
	}

}
